name: Docker

on:
  push:
    branches: [ "main" ]

env:
  REGISTRY: docker.io
  IMAGE_NAME: levk/mocha-headless-chrome-docker

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Create dated tag
        id: tag
        run: echo "::set-output name=tag::$(date +'%Y-%m-%d')"

      - uses: actions/checkout@v3
        name: Check out code

      - uses: mr-smithers-excellent/docker-build-push@v4.0
        name: Build & push Docker image
        with:
          image: levk/mocha-headless-chrome-docker
          tags: ${{ steps.tag.outputs.tag }},latest
          registry: docker.io
          dockerfile: Dockerfile
          username: levk
          password: ${{ secrets.DOCKER_TOKEN }}
